--- 
allowedItems: 
  - chest
  - crafting_table
  - oak_planks
  - stick
config: 
  debug: false
  enableHorsePerk: true
  helpChestCords: 
    - 0
    - 0
    - 0
  message: "&7[rpgCraftPerm] &cВы не умеете создавать &o&f%item%."
  notifyPlayer: true
disallowedBlocks: 
  - furnace
  - smoker
  - enchanting_table
groups: 
  Fisherman: 
    0: 
      - oak_door
  Woodman: 
    0: 
      - oak_door
    1: 
      - oak_sign
